"""add cabin_id to bookings

Revision ID: 267e376d32c8
Revises: 454d1e26d9ee
Create Date: 2025-10-02 20:52:03.308140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267e376d32c8'
down_revision: Union[str, Sequence[str], None] = '454d1e26d9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cabin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'cabins', ['cabin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'cabin_id')
    # ### end Alembic commands ###
