"""add cabins table

Revision ID: 454d1e26d9ee
Revises: d6e9d237cf5f
Create Date: 2025-10-01 14:08:01.617226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '454d1e26d9ee'
down_revision: Union[str, Sequence[str], None] = 'be7ae3639eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price_weekdays', sa.Integer(), nullable=False),
    sa.Column('price_weekend', sa.Integer(), nullable=False),
    sa.Column('pool', sa.Boolean(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabins_id'), 'cabins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cabins_id'), table_name='cabins')
    op.drop_table('cabins')
    # ### end Alembic commands ###
