"""init tables

Revision ID: 7ba873980593
Revises: 
Create Date: 2025-09-16 14:39:17.096488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba873980593'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Добавляем колонку, но пока nullable
    op.add_column("bookings", sa.Column("room_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_bookings_room", "bookings", "rooms", ["room_id"], ["id"])

    # 2. Заполняем колонку для старых записей (например, дефолтный номер = 1)
    op.execute("UPDATE bookings SET room_id = 1 WHERE room_id IS NULL")

    # 3. Теперь делаем её NOT NULL
    op.alter_column("bookings", "room_id", nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
