"""begin work with booking rooms /booking

Revision ID: 9cec9861b05b
Revises: ef99bc332215
Create Date: 2025-10-07 21:05:01.095287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cec9861b05b'
down_revision: Union[str, Sequence[str], None] = 'ef99bc332215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('bookings', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('bookings_cabin_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'cabin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cabin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('bookings_cabin_id_fkey'), 'bookings', 'cabins', ['cabin_id'], ['id'])
    op.alter_column('bookings', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bookings', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
