"""Изменена Room и Booking, тест для формы поиска

Revision ID: be7ae3639eec
Revises: ebe398a4c8dd
Create Date: 2025-09-22 15:06:42.174417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be7ae3639eec'
down_revision: Union[str, Sequence[str], None] = 'ebe398a4c8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('rooms', 'capacity')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'room_id')
    # ### end Alembic commands ###
