"""add created_at to rooms

Revision ID: d22ee77e6d8b
Revises: 7ba873980593
Create Date: 2025-09-17 22:09:42.590985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22ee77e6d8b'
down_revision: Union[str, Sequence[str], None] = '7ba873980593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('rooms', 'tv',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'tv',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('rooms', 'created_at')
    # ### end Alembic commands ###
