"""add created_at and images to rooms

Revision ID: ebe398a4c8dd
Revises: d22ee77e6d8b
Create Date: 2025-09-18 20:08:59.720136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe398a4c8dd'
down_revision: Union[str, Sequence[str], None] = 'd22ee77e6d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # если данные не важны (очистим)
    op.execute("UPDATE rooms SET images = '[]';")

    # теперь меняем тип
    op.execute("""
        ALTER TABLE rooms
        ALTER COLUMN images
        TYPE JSON
        USING images::json;
    """)




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'images',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
