"""replace room_id with object_type and object_id

Revision ID: ef99bc332215
Revises: 267e376d32c8
Create Date: 2025-10-04 21:00:55.907776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef99bc332215'
down_revision: Union[str, Sequence[str], None] = '267e376d32c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('object_type', sa.String(), nullable=False))
    op.add_column('bookings', sa.Column('object_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_room'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_room'), 'bookings', 'rooms', ['room_id'], ['id'])
    op.drop_column('bookings', 'object_id')
    op.drop_column('bookings', 'object_type')
    # ### end Alembic commands ###
